---
name: Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-12, gcc-13, clang-17, clang-18]
    env:
      PREFIX: /usr/local/bin
      CC: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            pkg-config \
            libglib2.0-dev \
            liblua5.4-dev \
            libwnck-3-dev \
            libgtk-3-dev \
            libxrandr-dev \
            build-essential \
            gettext \
            clang-17 \
            clang-18 \
            gcc-12 \
            gcc-13
      - name: CC ver
        run: ${CC} -v
      - name: make
        run: make
      - name: make install
        run: sudo make install
      - name: ldd
        run: ldd $PREFIX/devilspie2
      - name: check version
        run: $PREFIX/devilspie2 -v
      - name: check libwnck version
        run: $PREFIX/devilspie2 -w
      - name: check Lua version
        run: $PREFIX/devilspie2 -l
